### ISSUE TITLE
Problem with closing server properly

### ISSUE THREAD

**Issue by turdusmerula** [zaphoyd/websocketpp#506] opened 2016-01-17 23:21 UTC
I have a problem partially related to the issue #410 but as it's not exactly the same I'm trying here a new issue.

I run on my debian jessy a multithreaded server simply launched by calling `websocketpp::server<Config>::run` in several threads, all works pretty fine until I try to shut it down.
My shutting down sequence is as follow, in the main thread I do:
 1- `stop_listening()` ;
 2- set `closing=true`, it prevents any new connection by closing it immediately
 3- iterate over each connection and send `close(conn.second->hdl_, websocketpp::close::status::going_away, "Server shuting down") ;`
 4- exiting the process nicely

If the server never encountered any connection all works perfectly. 
If at least one connection is active then I see it closing at the client side, then the server exits but the socket remains in the TIME_WAIT status until timeout.
Output of `netstat -np | grep 8200`
`tcp6       0      0 10.0.3.238:8200         10.0.3.1:52052          TIME_WAIT   -               `

This problem needs only one client connection to happen.

Am I forgetting something in my closing sequence?

**Comment by zaphoyd** [comment] 2016-01-31 19:10
You are not forgetting anything. What you describe is the intended behavior. When TCP connections (such as WebSocket connections) are closed, the peer that initiated the close will enter the `TIME_WAIT` state. This is an expected part of the TCP protocol and is not an error. The purpose is so that any delayed or missing packets that wind up at the server after the connection is closed are recognized as such and safely discarded without interfering with other connections.

The WebSocket protocol specifically stipulates (RFC6455 7.1.1) that the server should initiate the TCP closing handshake to ensure that it enters the `TIME_WAIT` state rather than the client. The goal here is to ensure that the client can rapidly reconnect (which otherwise wouldn't be possible if the client had to wait for a local `TIME_WAIT` on the server port to clear). This is not a problem for the server because incoming connections are assigned a random free port whereas the client must connect to the port the server is listening on.

**Closed by zaphoyd** 2016-01-31 19:10 UTC

**Comment by turdusmerula** [comment] 2016-01-31 21:25
Those `TIME_WAIT` sockets were preventing me to restart my server until timeout, but indeed I had the wrong analysis for that. 
Just discovered I forgot to the `set_reuse_addr(true)`, this solved my restart problems.

Thank you.
