### ISSUE TITLE
SSL connection (wss://) speed

### ISSUE THREAD

**Issue by maggnetz** [zaphoyd/websocketpp#405] opened 2015-02-22 09:16 UTC
i started using this library,got a very good results but when moved to SSL connections started to get very slow response. (Im using well sign SSL from a real CA)
for example (doing ping->echoserver->ping result) times: (All is same server,same location,same SSL cert)

iis ws - 17ms
iis wss - 18ms
node ws - 17ms
node wss - 18ms-19ms
websocketpp ws - 17ms-18ms
<b>websocketpp wss - 80ms-90ms</b>

any ideas??

**Comment by amdei** [comment] 2015-04-16 17:39
Did you measire full circle (SSL handshake + ping), or subsequent ping only?

**Comment by maggnetz** [comment] 2015-04-16 20:34
full circle -> i open socket -> send a message "hello" -> server answer
"you too" -> and time stamp for it (Echo server)

**Comment by amdei** [comment] 2015-04-17 02:26
What client system, compiller, boost & OpenSSL versions do you use?

First thing - I would distinguish delays in SSL connection establishing and delays in actual data transfer.
Do you able to repeat your test with measuring these two operation times separatelly?

**Comment by maggnetz** [comment] 2015-04-17 02:41
Server 2012 , VS 2103 SP3,boost the latested.
I didn't invest time on find the where it's happening.

but same conditions , http works fine.
same condition's https Node server works great (Currently i'm already in
production with node)

**Comment by zaphoyd** [comment] 2020-06-30 10:56
This is almost certainly a duplicate of #626. There is more discussion and context there about what is happening.

**Closed by zaphoyd** 2020-06-30 10:56 UTC
Labels: Performance Issue

**Comment by newpoo** [comment] 2023-05-14 05:00
> This is almost certainly a duplicate of #626. There is more discussion and context there about what is happening.

@zaphoyd has this issue been resolved? any recommendation to get around it?
