### ISSUE TITLE
Does not compile on new Xcode 7 beta

### ISSUE THREAD

**Issue by leecbaker** [zaphoyd/websocketpp#434] opened 2015-06-10 06:42 UTC
Compiling with the latest Apple developer tools beta fails. Error is:
```
In file included from ../websocketpp/websocketpp/config/asio_no_tls.hpp:31:
In file included from ../websocketpp/websocketpp/config/core.hpp:43:
In file included from ../websocketpp/websocketpp/http/request.hpp:34:
In file included from ../websocketpp/websocketpp/http/parser.hpp:36:
In file included from ../websocketpp/websocketpp/utilities.hpp:180:
../websocketpp/websocketpp/impl/utilities_impl.hpp:39:5: error: no matching function for call to 'transform'
    std::transform(out.begin(),out.end(),out.begin(),::tolower);
    ^~~~~~~~~~~~~~
In file included from omitted.cpp:1:
In file included from omitted.h:4:
In file included from /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/string:439:
/Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/algorithm:1957:1: note: candidate template ignored: couldn't infer template argument '_UnaryOperation'
transform(_InputIterator __first, _InputIterator __last, _OutputIterator __result, _UnaryOperation __op)
^
/Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/algorithm:1967:1: note: candidate function template not viable: requires 5 arguments, but 4 were provided
transform(_InputIterator1 __first1, _InputIterator1 __last1, _InputIterator2 __first2,
```
Xcode: Version 7.0 beta (7A120f)
Apple LLVM version 7.0.0 (clang-700.0.53)
Target: x86_64-apple-darwin14.3.0

The following trivial workaround compiles ok as a substitute for the transform function:

    for(char c : out) {
        c = ::tolower(c);
    }

**Comment by zaphoyd** [comment] 2015-11-05 11:37
Using the final build of Xcode 7, I am unable to reproduce this. Can anyone else confirm? Was this something that ended up being fixed by Apple?

**Comment by astoeckley** [comment] 2015-12-27 20:36
FWIW I am using websocket++ with Xcode 7 as both client and server and no problems...

**Comment by zaphoyd** [comment] 2016-01-31 20:51
I've had no problems with the release version either. If anyone has further issues they should reopen.

**Closed by zaphoyd** 2016-01-31 20:51 UTC
